language: php
php:
    - 5.5
    - 5.4
    - 5.3
    - hhvm

install:
    - composer install

script:
    - make test

matrix:
    allow_failures:
        # until hhvm supports closures correctly
        - hhvm
